/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import programacion.conexionSQL;

/**
 *
 * @author hp
 */
public class ingreso_merc extends javax.swing.JFrame {

 
    conexionSQL cc= new conexionSQL();
        Connection con = cc.conexion();
        
    public ingreso_merc() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    int buscar(){
          String a= id_productotxt.getText();
        String sql;
        String psn=new String();
        String psu=new String();
        String psp=new String();
        String psc=new String();
        
        
        
        try {
         sql="SELECT Nombre,ubicacion,Precio,Cantidad FROM productos WHERE ID_producto LIKE '" +a+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                
                psn= rs.getString(1);
                psu= rs.getString(2);
                psp= rs.getString(3);
                psc= rs.getString(4);
                if( psc.equals("")){
                Nombretxt.setText(psn);
                Ubicaciontxt.setText(psu);
                preciotxt.setText(psp);
                cantidadtxt.setText(psc);
                agregarnuevo();
                }else{
                Nombretxt.setText(psn);
                Ubicaciontxt.setText(psu);
                preciotxt.setText(psp);
                cantidadtxt.setText(String.valueOf(calcula(psc,JOptionPane.showInputDialog(cantidadtxt, "Ingrese nueva cantidad"))));
                
                }
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ingreso_merc.class.getName()).log(Level.SEVERE, null, ex);
        }
       return 0; 
        
    }
    void agregarnuevo(){
        try {
            PreparedStatement pps = con.prepareStatement("INSERT INTO productos(ID_producto,nombre,ubicacion,Precio,Cantidad) VALUES(?,?,?,?,?)");
            pps.setString(1, id_productotxt.getText());
             pps.setString(2, Nombretxt.getText());
              pps.setString(3, Ubicaciontxt.getText());
               pps.setString(4, preciotxt.getText());
                pps.setString(5, cantidadtxt.getText());
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "datos guardados correctamente");
                id_productotxt.setText(null);
                Nombretxt.setText(null);
                Ubicaciontxt.setText(null);
                preciotxt.setText(null);
                cantidadtxt.setText(null);
                
                        
                
        } catch (SQLException ex) {
            Logger.getLogger(ingreso_merc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void modifica(){
        try {
            PreparedStatement cuenta=con.prepareStatement("UPDATE productos set Cantidad='"+cantidadtxt.getText()+"'WHERE ID_producto LIKE'"+id_productotxt.getText()+"'");
            cuenta.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inventario Exitoso");
                id_productotxt.setText(null);
                Nombretxt.setText(null);
                Ubicaciontxt.setText(null);
                preciotxt.setText(null);
                cantidadtxt.setText(null);
            
        } catch (SQLException ex) {
            Logger.getLogger(ingreso_merc.class.getName()).log(Level.SEVERE, null, ex);
        }
}   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_productotxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ubicaciontxt = new javax.swing.JTextField();
        Nombretxt = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        preciotxt = new javax.swing.JTextField();
        cantidadtxt = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID_producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 87, 23));
        getContentPane().add(id_productotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 11, 170, 23));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 52, 87, 29));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("precio");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 87, 25));

        Ubicaciontxt.setEnabled(false);
        getContentPane().add(Ubicaciontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 97, 110, 23));

        Nombretxt.setEnabled(false);
        getContentPane().add(Nombretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 52, 170, 23));

        agregar.setText("agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 270, 176, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 30, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 87, 25));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ubicacion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 87, 25));

        preciotxt.setEnabled(false);
        getContentPane().add(preciotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 130, 30));

        cantidadtxt.setEnabled(false);
        getContentPane().add(cantidadtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, 30));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 140, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fm2.gif"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicio a=new inicio();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        modifica();
        
    }//GEN-LAST:event_agregarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
      buscar();
      Nombretxt.setEnabled(true);
      Ubicaciontxt.setEnabled(true);
      cantidadtxt.setEnabled(true);
      preciotxt.setEnabled(true);
      
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingreso_merc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingreso_merc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingreso_merc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingreso_merc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingreso_merc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField Nombretxt;
    private javax.swing.JTextField Ubicaciontxt;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cantidadtxt;
    private javax.swing.JTextField id_productotxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField preciotxt;
    // End of variables declaration//GEN-END:variables

    private int calcula(String a, String b) {
        int res=0;
        res= Integer.valueOf(a) + Integer.valueOf(b);
        return res;
      
    }
}
