/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import com.mysql.jdbc.ResultSet;
import java.sql.Connection;
import java.sql.JDBCType;
import static java.sql.JDBCType.NULL;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView;
import programacion.conexionSQL;

/**
 *
 * @author hp
 */
public class Punto_venta extends javax.swing.JFrame {

    /**
     * Creates new form Punto_venta
     */
    public Punto_venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    protected conexionSQL cc = new conexionSQL();
    protected Connection con = cc.conexion();

    protected ArrayList<Object> prducto = new ArrayList<>();
    
    float total;
    

    void agregarnuevo(String a, String b) {
        try {
            PreparedStatement pps = con.prepareStatement("INSERT INTO venta(ID_producto,nombre,ubicacion,Precio,Cantidad) VALUES(?,?,?,?,?)");

        } catch (SQLException ex) {
            Logger.getLogger(ingreso_merc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void getid(String id) {
        String producto, precio, total;
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id_producto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");

        try {
            String sql = "SELECT Nombre,Precio FROM productos WHERE ID_producto LIKE '" + id + "'";
            Statement st = con.createStatement();
            ResultSet rs = (ResultSet) st.executeQuery(sql);
            while (rs.next()) {
                producto = rs.getString(1);
                precio = rs.getString(2);
                System.out.println("precio" + precio + "," + "producto" + producto);

            }

        } catch (Exception e) {
        }

    }

    public void tabla() {
        int tamaño = prducto.size();
        total=0;
        Object matriz[][] = new Object[tamaño][3];
        for (int i = 0; i < tamaño; i++) {
            String a[] = (String[]) prducto.get(i);
            matriz[i][0] = Integer.parseInt(a[0]);
            matriz[i][1] = a[1]+"";
            matriz[i][2] = Float.parseFloat(a[2]);
            total+=Float.parseFloat(a[2]);
        }
        Total.setText(total+"");
        
        Tabla.setModel(new javax.swing.table.DefaultTableModel(matriz, new String[]{
            "id", "Nombre", "Precio"
        }) {
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            boolean canEdit[] = new boolean[]{
                false, false, true
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            @Override
            public boolean  isCellEditable(int rowIndex,int columnIndex) {
                return canEdit[columnIndex];
            }
        });
    }

    public void Mostrar(String id) {
       

       

        String SQL = "";

        if (id.equals("")) {
            SQL = "SELECT ID_producto,Nombre,Precio FROM productos";

        } else {
            SQL = "SELECT ID_producto,Nombre,Precio FROM productos WHERE ID_producto LIKE '" + id + "'";

        }
        try {
            Statement set = con.createStatement();
            ResultSet rs = (ResultSet) set.executeQuery(SQL);

            while (rs.next()) {
                String producto[] = new String[3];
                producto[0] = rs.getString(1);
                producto[1] = rs.getString(2);
                producto[2] = rs.getString(3);

                prducto.add(producto);

            }
            tabla();

        } catch (SQLException ex) {
            Logger.getLogger(Punto_venta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        consulta = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        Cambia_producto = new javax.swing.JButton();
        subtotal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Codigo = new javax.swing.JTextField();
        agr = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 559, 97));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 67));

        consulta.setText("consultar productos");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        getContentPane().add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 160, 60));

        eliminar.setText("Eliminar producto");
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 151, 60));

        Cambia_producto.setText("Cambiar");
        getContentPane().add(Cambia_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 150, 60));

        subtotal.setText("subtotal");
        subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 158, 55));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_e_Imagenes/Imagenes interfaz/Exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 0, 30, 20));

        Codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoKeyTyped(evt);
            }
        });
        getContentPane().add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 330, 30));

        agr.setText("agregar");
        agr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agrActionPerformed(evt);
            }
        });
        getContentPane().add(agr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        Total.setForeground(new java.awt.Color(255, 255, 255));
        Total.setText("jLabel3");
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fm2.gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        inicio a = new inicio();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        consulta a = new consulta();
        a.setVisible(true);
        this.dispose();
        Mostrar("");

    }//GEN-LAST:event_consultaActionPerformed

    private void subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotalActionPerformed


    }//GEN-LAST:event_subtotalActionPerformed

    private void CodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoKeyTyped


    }//GEN-LAST:event_CodigoKeyTyped

    private void CodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoKeyReleased

    }//GEN-LAST:event_CodigoKeyReleased

    private void agrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agrActionPerformed
        Mostrar(Codigo.getText());
    }//GEN-LAST:event_agrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punto_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punto_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punto_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punto_venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punto_venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cambia_producto;
    private javax.swing.JTextField Codigo;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel Total;
    private javax.swing.JButton agr;
    private javax.swing.JButton consulta;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton subtotal;
    // End of variables declaration//GEN-END:variables
}
